### ISSUE TITLE
Missing captions for self shout and relay

### ISSUE THREAD

**Issue by kaleko** [breakone9r/mmpkg#6]
Screenshot attached here: https://postimg.cc/gallery/hqxg23j

**Comment by breakone9r** [comment]
I don't HAVE a shout tab at all. It shouldn't be tracked in the slightest.

As for the other, did you by chance turn off the relays tab? It's SUPPOSED to also disable the associated trigger, and it may not have.

**Comment by breakone9r** [comment]
I'm about to upload a possible fix this. The triggers should not become unsynched, but now I force it so upon load. It'll read what tabs are enabled, and enable/disable the associated triggers at load.

**Comment by breakone9r** [comment]
If there's no more data, I will mark this as closed as fixed in 1.4.2.
